import type { Player } from "./game-types";

// These imports use dynamic require at runtime so both client and PartyKit
// workers can consume them. The sample dataset ships with the repo; the real
// one is generated by `pnpm build-dataset` and is gitignored.
import sample from "../../public/players.sample.json";

let cache: Player[] | null = null;

/** Load the full player pool. Returns sample dataset if the real file isn't built yet. */
export function loadPlayers(): Player[] {
  if (cache) return cache;
  // In Next.js we can fetch players.json at runtime, but to keep things simple
  // and to make the data available inside PartyKit workers (which can't read
  // the filesystem), we bake the sample in as an import. Swap imports to the
  // full dataset in your app after running the build script.
  cache = sample as Player[];
  return cache;
}

/** Only real-world usable players (has overall, has position, has a name). */
export function usablePlayers(): Player[] {
  return loadPlayers().filter((p) => p.ovr >= 65 && p.pos && p.name);
}

export function byPosition(pos: string): Player[] {
  return usablePlayers().filter((p) => p.pos === pos);
}

const POSITION_GROUPS: Record<"GK" | "DEF" | "MID" | "FWD", readonly string[]> = {
  GK: ["GK"],
  DEF: ["CB", "LB", "RB", "LWB", "RWB"],
  MID: ["CDM", "CM", "CAM", "LM", "RM"],
  FWD: ["ST", "CF", "LW", "RW"],
};

export function byPositionGroup(group: "GK" | "DEF" | "MID" | "FWD"): Player[] {
  const positions = POSITION_GROUPS[group];
  return usablePlayers().filter((p) => positions.includes(p.pos));
}

export function findPlayer(id: string): Player | undefined {
  return loadPlayers().find((p) => p.id === id);
}

/** Quick autocomplete search used by Playerdle. */
export function searchPlayers(query: string, limit = 8): Player[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return usablePlayers()
    .filter((p) => p.name.toLowerCase().includes(q))
    .sort((a, b) => b.ovr - a.ovr)
    .slice(0, limit);
}
